# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Prometheus
    uid: AS_Solo_Proj1
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true